version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    volumes:
      - db:/data/db
    networks:
      - nxc_default

  text-me:
    build: ./app
    restart: always
    ports:
      - 8088:8080
    depends_on:
      - mongo
    networks:
      - nxc_default

networks:
  nxc_default:
    external: true

volumes:
  db:
